DROP TABLE IF EXISTS FOREIGN_EXCHANGE;

CREATE TABLE FOREIGN_EXCHANGE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CURRENCY VARCHAR(250) DEFAULT NULL,
  OBS_VALUE VARCHAR(250) DEFAULT NULL,
  BBK_DIFF VARCHAR(250) DEFAULT NULL,
  BBK_OBS_STATUS VARCHAR(250) DEFAULT NULL,
  DATE DATE
);